version = 1

exclude_patterns = ["sdk/build/**", "example-app/**"]

test_patterns = ["**/test/**"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "kotlin"

[analyzers.meta]
runtime_version = "1.8"
language_version = "1.9"

[[analyzers]]
name = "java"

[analyzers.meta]
runtime_version = "17"
