default_stages: [commit]
repos:
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: 'v9.10.0'
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies:
                - '@commitlint/cli'
                - '@commitlint/config-conventional'
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 'v4.5.0'
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            exclude: '.idea/modules'
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v3.1.0'
      hooks:
          - id: prettier
            exclude: '.idea/modules'
