version: '3'

tasks:
    setup:
        desc: Setup the project dependencies
        cmds:
            - command -v pre-commit &> /dev/null || brew install pre-commit
            - pre-commit install && pre-commit install --hook-type commit-msg && pre-commit install-hooks
    update:
        cmds:
            - pre-commit autoupdate
            - ./gradlew wrapper --gradle-version latest
            - ./gradlew androidDependencies
            - ./gradlew versionCatalogUpdate
    lint:
        desc: Lint the project
        cmds:
            - pre-commit run --show-diff-on-failure --color=always --all-files
            - ./gradlew :sdk:lint
            - ./gradlew :example-app:lint
            - ./gradlew spotlessApply
