name: 'Validate'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: gradle
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 21
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'
            - name: Install Task
              uses: arduino/setup-task@v1
            - name: Install Pre-Commit
              run: python -m pip install pre-commit && pre-commit install
            - name: Load Cached Pre-Commit Dependencies
              id: cached-pre-commit-dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pre-commit/
                  key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
            - name: Enable gradlew execution
              run: chmod +x gradlew
            - name: Lint
              run: task lint
